---
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.25
      
      - run: |     
          ls 
          pwd
          whoami

          cd test
          terraform plan -out plan.out

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test/plan.out
          retention-days: 5
